const specialChars = ["@", "#", "-", "!", "\"", "$", "%", "&", "'", "(", ")", "*", "+", ",", ".", "/", ":", ";", "<", "=", ">", "?", "[", "\\", "]", "^", "_", "{", "|", "}", "~"];


const nums = ["1", "2", "3", "4", "5", "6", "7", "8", "9"];

const twoLetterWords = [
    "am", "an", "as", "at", "be", "by", "do", "go", "he", "if", "in", "is", "it", "me", "my", "no", "of", "on", "or", 
    "so", "to", "up", "us", "we"
];

const twoLetterWordsCaps = [
    "Am", "An", "As", "At", "Be", "By", "Do", "Go", "He", "If", "In", "Is", "It", "Me", "My", "No", "Of", "On", 
    "Or", "So", "To", "Up", "Us", "We"
];


const threeLetterWords = [
    "act", "add", "age", "ago", "aid", "aim", "air", "amp", "and", "any", "ape", "app", "apt", "arc", "are", 
    "ark", "arm", "art", "ask", "axe", "bad", "bag", "bar", "bat", "bay", "bed", "bet", "big", "bin", "bit", 
    "boa", "bob", "bog", "boo", "box", "boy", "bra", "bug", "bum", "bus", "but", "buy", "bye", "cab", "can", 
    "cap", "car", "cat", "cob", "cod", "cop", "cot", "cow", "coy", "cry", "cub", "cup", "cut", "dad", "dam", 
    "day", "den", "dig", "dim", "dip", "dog", "dot", "dry", "dub", "dud", "due", "dug", "ear", "eat", "eel", 
    "egg", "elf", "elm", "end", "eon", "era", "eve", "eye", "fan", "far", "fat", "fax", "fed", "fee", "few", 
    "fig", "fin", "fir", "fit", "fix", "fly", "foe", "fog", "for", "fox", "fry", "fun", "fur", "gag", "gap", 
    "gas", "gay", "gel", "gem", "get", "gin", "god", "got", "gum", "gun", "gut", "guy", "gym", "had", "ham", 
    "hat", "hay", "hem", "hen", "hey", "hip", "hit", "hog", "hop", "hot", "how", "hub", "hue", "hug", "hum", 
    "hut", "ice", "icy", "ill", "ink", "inn", "ion", "its", "ivy", "jab", "jam", "jar", "jaw", "jet", "jig", 
    "job", "jog", "joy", "jug", "keg", "key", "kid", "kin", "kit", "lab", "lad", "lag", "lap", "law", "lay", 
    "led", "leg", "let", "lid", "lie", "lip", "lit", "log", "lot", "low", "mad", "man", "map", "mat", "max", 
    "may", "men", "met", "mew", "mid", "mix", "mob", "mom", "moo", "mop", "mud", "mug", "nap", "net", "new", 
    "nil", "nip", "nit", "nod", "nor", "not", "now", "nut", "oak", "oar", "oat", "odd", "off", "oil", "old", 
    "one", "opt", "orb", "ore", "our", "out", "owe", "owl", "own", "pad", "pal", "pan", "paw", "pay", "peg", 
    "pen", "pet", "pie", "pig", "pin", "pit", "ply", "pod", "pot", "pro", "pun", "pup", "put", "rad", "rag", 
    "ram", "ran", "rap", "rat", "raw", "ray", "red", "rib", "rid", "rig", "rim", "rip", "rob", "rod", "rot", 
    "row", "rub", "rug", "rum", "run", "rut", "rye", "sad", "sap", "sat", "say", "sea", "see", "set", "sew", 
    "sex", "she", "shy", "sin", "sip", "sit", "ski", "sky", "sly", "sob", "son", "sow", "soy", "spa", "spy", 
    "sum", "sun", "tab", "tag", "tan", "tap", "tax", "tea", "ten", "the", "thy", "tic", "tie", "tin", "tip", 
    "toe", "tom", "ton", "too", "top", "toy", "try", "tub", "tug", "two", "urn", "use", "van", "vet", "vie", 
    "wag", "war", "way", "wed", "wet", "who", "why", "wig", "win", "wit", "wok", "won", "wow", "yak", "yam", 
    "yen", "yes", "yet", "yew", "you", "yum", "zap", "zip", "zoo"
];

const threeLetterWordsCaps = [
    "Act", "Add", "Age", "Ago", "Aid", "Aim", "Air", "Amp", "And", "Any", "Ape", "App", "Apt", "Arc", "Are",
    "Ark", "Arm", "Art", "Ask", "Axe", "Bad", "Bag", "Bar", "Bat", "Bay", "Bed", "Bet", "Big", "Bin", "Bit",
    "Boa", "Bob", "Bog", "Boo", "Box", "Boy", "Bra", "Bug", "Bum", "Bus", "But", "Buy", "Bye", "Cab", "Can",
    "Cap", "Car", "Cat", "Cob", "Cod", "Cop", "Cot", "Cow", "Coy", "Cry", "Cub", "Cup", "Cut", "Dad", "Dam",
    "Day", "Den", "Dig", "Dim", "Dip", "Dog", "Dot", "Dry", "Dub", "Dud", "Due", "Dug", "Ear", "Eat", "Eel",
    "Egg", "Elf", "Elm", "End", "Eon", "Era", "Eve", "Eye", "Fan", "Far", "Fat", "Fax", "Fed", "Fee", "Few",
    "Fig", "Fin", "Fir", "Fit", "Fix", "Fly", "Foe", "Fog", "For", "Fox", "Fry", "Fun", "Fur", "Gag", "Gap",
    "Gas", "Gay", "Gel", "Gem", "Get", "Gin", "God", "Got", "Gum", "Gun", "Gut", "Guy", "Gym", "Had", "Ham",
    "Hat", "Hay", "Hem", "Hen", "Hey", "Hip", "Hit", "Hog", "Hop", "Hot", "How", "Hub", "Hue", "Hug", "Hum",
    "Hut", "Ice", "Icy", "Ill", "Ink", "Inn", "Ion", "Its", "Ivy", "Jab", "Jam", "Jar", "Jaw", "Jet", "Jig",
    "Job", "Jog", "Joy", "Jug", "Keg", "Key", "Kid", "Kin", "Kit", "Lab", "Lad", "Lag", "Lap", "Law", "Lay",
    "Led", "Leg", "Let", "Lid", "Lie", "Lip", "Lit", "Log", "Lot", "Low", "Mad", "Man", "Map", "Mat", "Max",
    "May", "Men", "Met", "Mew", "Mid", "Mix", "Mob", "Mom", "Moo", "Mop", "Mud", "Mug", "Nap", "Net", "New",
    "Nil", "Nip", "Nit", "Nod", "Nor", "Not", "Now", "Nut", "Oak", "Oar", "Oat", "Odd", "Off", "Oil", "Old",
    "One", "Opt", "Orb", "Ore", "Our", "Out", "Owe", "Owl", "Own", "Pad", "Pal", "Pan", "Paw", "Pay", "Peg",
    "Pen", "Pet", "Pie", "Pig", "Pin", "Pit", "Ply", "Pod", "Pot", "Pro", "Pun", "Pup", "Put", "Rad", "Rag",
    "Ram", "Ran", "Rap", "Rat", "Raw", "Ray", "Red", "Rib", "Rid", "Rig", "Rim", "Rip", "Rob", "Rod", "Rot",
    "Row", "Rub", "Rug", "Rum", "Run", "Rut", "Rye", "Sad", "Sap", "Sat", "Say", "Sea", "See", "Set", "Sew",
    "Sex", "She", "Shy", "Sin", "Sip", "Sit", "Ski", "Sky", "Sly", "Sob", "Son", "Sow", "Soy", "Spa", "Spy",
    "Sum", "Sun", "Tab", "Tag", "Tan", "Tap", "Tax", "Tea", "Ten", "The", "Thy", "Tic", "Tie", "Tin", "Tip",
    "Toe", "Tom", "Ton", "Too", "Top", "Toy", "Try", "Tub", "Tug", "Two", "Urn", "Use", "Van", "Vet", "Vie",
    "Wag", "War", "Way", "Wed", "Wet", "Who", "Why", "Wig", "Win", "Wit", "Wok", "Won", "Wow", "Yak", "Yam",
    "Yen", "Yes", "Yet", "Yew", "You", "Yum", "Zap", "Zip", "Zoo"
];


const fourLetterWords = [
    "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball", "band", "bank", "base", 
    "bath", "bear", "beat", "been", "bell", "belt", "best", "bill", "bird", "blow", "blue", "boat", "body", 
    "bomb", "bone", "book", "born", "boss", "both", "bowl", "bulk", "burn", "bush", "busy", "call", "calm", 
    "came", "camp", "card", "care", "case", "cash", "cast", "cell", "cent", "chat", "chip", "city", "club", 
    "coal", "coat", "code", "cold", "come", "cook", "cool", "cope", "copy", "core", "cost", "crew", "crop", 
    "dark", "data", "date", "dead", "deal", "dear", "debt", "deep", "desk", "diet", "disc", "dish", "disk", 
    "door", "draw", "drop", "drug", "dust", "duty", "each", "earn", "ease", "east", "easy", "edge", "else", 
    "even", "ever", "evil", "exit", "face", "fact", "fair", "fall", "farm", "fast", "fate", "fear", "feed", 
    "feel", "feet", "fell", "felt", "file", "fill", "film", "find", "fine", "fire", "firm", "fish", "five", 
    "flat", "flow", "food", "foot", "form", "fort", "four", "free", "from", "fuel", "full", "fund", "gain", 
    "game", "gate", "gear", "gene", "gift", "girl", "give", "glad", "goal", "gold", "good", "gray", "grow", 
    "hair", "half", "hand", "hang", "hard", "have", "head", "hear", "heat", "help", "here", "high", "hold", 
    "home", "hope", "host", "hour", "huge", "hunt", "hurt", "idea", "inch", "into", "iron", "item", "join", 
    "jump", "jury", "just", "keep", "kick", "kill", "kind", "king", "knee", "know", "land", "last", "late", 
    "lead", "leaf", "lean", "left", "less", "life", "lift", "like", "line", "link", "list", "live", "load", 
    "loan", "lock", "long", "look", "lose", "loss", "love", "luck", "main", "make", "male", "many", "mark", 
    "mass", "meal", "mean", "meet", "menu", "mere", "mild", "mile", "milk", "mill", "mind", "mine", "miss", 
    "mode", "mood", "moon", "more", "most", "move", "much", "must", "name", "near", "neck", "need", "news", 
    "next", "nice", "nine", "none", "nose", "note", "okay", "once", "only", "onto", "open", "oral", "over", 
    "pace", "pack", "page", "pain", "pair", "pale", "park", "part", "pass", "past", "path", "peak", "pick", 
    "pink", "plan", "play", "plot", "plus", "pool", "port", "post", "pour", "pull", "pure", "push", "race", 
    "rail", "rain", "rank", "rare", "rate", "read", "real", "rear", "rely", "rent", "rest", "rich", "ride", 
    "ring", "rise", "risk", "road", "rock", "role", "roll", "roof", "room", "root", "rope", "rose", "rule", 
    "rush", "safe", "said", "sale", "salt", "same", "sand", "save", "seat", "seed", "seek", "seem", "self", 
    "sell", "send", "sent", "ship", "shop", "shot", "show", "shut", "sick", "side", "sign", "silk", "sing", 
    "sink", "site", "size", "skin", "slip", "slow", "snow", "soft", "soil", "sold", "sole", "some", "song", 
    "soon", "sort", "soul", "spot", "star", "stay", "step", "stop", "such", "suit", "sure", "take", "talk", 
    "tall", "tank", "tape", "task", "team", "tell", "term", "test", "text", "than", "that", "them", "then", 
    "they", "thin", "this", "thus", "till", "time", "tiny", "told", "toll", "tone", "tool", "tour", "town", 
    "tree", "trip", "true", "turn", "type", "unit", "upon", "used", "user", "vary", "vast", "very", "view", 
    "vote", "wait", "wake", "walk", "wall", "want", "warm", "warn", "wash", "wave", "weak", "wear", "week", 
    "well", "went", "were", "west", "what", "when", "whom", "wide", "wife", "wild", "will", "wind", "wine", 
    "wing", "wire", "wise", "wish", "with", "wood", "word", "worn", "yard", "yeah", "year", "yell", "your", 
    "zero", "zone"
];

const fiveLetterWords = [
    "about", "above", "actor", "acute", "admit", "adopt", "adult", "after", "again", "agent", "agree", "ahead", 
    "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along", "alter", "among", "anger", "angle", 
    "angry", "ankle", "apart", "apple", "apply", "arena", "argue", "arise", "array", "aside", "asset", "audio", 
    "audit", "avoid", "award", "aware", "basic", "basis", "beach", "began", "begin", "begun", "being", "below", 
    "bench", "billy", "birth", "black", "blade", "blame", "blank", "blast", "blend", "bless", "blind", "block", 
    "blood", "board", "boost", "booty", "bored", "bound", "brain", "brave", "bread", "break", "breed", "brick", 
    "brief", "bring", "broad", "brown", "brush", "bunch", "buyer", "cabin", "cable", "candy", "carry", "chain", 
    "chair", "chart", "chase", "cheap", "check", "cheek", "cheer", "chief", "child", "chose", "civil", "claim", 
    "class", "clean", "clear", "clerk", "click", "clock", "close", "cloth", "cloud", "coach", "coast", "could", 
    "count", "court", "cover", "craft", "crash", "crawl", "cream", "crime", "cross", "crowd", "crown", "curve", 
    "cycle", "daily", "dance", "dated", "death", "debit", "debut", "decay", "decor", "delay", "depth", 
    "diary", "dirty", "diver", "doing", "doubt", "draft", "dream", "dress", "drink", "drive", "drove", 
    "drown", "eager", "early", "earth", "eight", "elder", "elect", "elite", "empty", "enemy", "enjoy", "enter", 
    "entry", "equal", "error", "essay", "event", "every", "exact", "exist", "extra", "faith", "false", "fault", 
    "favor", "fifth", "fight", "final", "first", "fixed", "flash", "fleet", "flesh", "flight", "float", "floor", 
    "fluid", "focus", "force", "forth", "forty", "forum", "found", "frame", "fresh", "front", "fruit", "funny", 
    "giant", "given", "glass", "globe", "going", "grace", "grade", "grand", "grant", "grass", "great", "green", 
    "greet", "guard", "guess", "guest", "guide", "habit", "happy", "heart", "heavy", "hello", "honor", "hotel", 
    "house", "human", "ideal", "image", "index", "inner", "input", "issue", "joint", "judge", "juice", "known", 
    "large", "later", "laugh", "layer", "learn", "least", "leave", "legal", "level", "light", "limit", "local", 
    "logic", "lover", "lucky", "lunch", "lying", "magic", "major", "maker", "march", "match", "maybe", "media", 
    "metal", "might", "minor", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth", "movie", 
    "music", "naked", "named", "nasty", "naval", "never", "night", "noise", "north", "noted", "novel", "nurse", 
    "occur", "ocean", "offer", "often", "older", "onion", "order", "ought", "owner", "paint", "panel", "panic", 
    "paper", "party", "peace", "piano", "phone", "photo", "piece", "place", "plain", "plant", "plate", "point", 
    "pound", "power", "press", "price", "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove", 
    "quote", "radio", "raise", "range", "rapid", "ratio", "reach", "ready", "realm", "rebel", "refer", "relax", 
    "relay", "reply", "right", "rival", "river", "robot", "rocky", "royal", "rural", "scale", "scene", "score", 
    "sense", "serve", "seven", "shake", "shame", "shape", "share", "sharp", "sheep", "sheet", "shelf", "shell", 
    "shift", "shirt", "shock", "shoot", "shore", "short", "shout", "sight", "since", "sixty", "skill", "sleep", 
    "slide", "small", "smart", "smile", "smoke", "solid", "solve", "sound", "south", "space", "spare", "speak", 
    "speed", "spend", "spent", "split", "sport", "staff", "stage", "stair", "stand", "start", "state", "steam", 
    "steel", "steep", "stick", "still", "stock", "stone", "stood", "store", "storm", "story", "strip", "study", 
    "stuff", "style", "sugar", "sunny", "super", "table", "taken", "taste", "teach", "thank", "theme", "there", 
    "these", "thick", "thing", "think", "third", "those", "three", "throw", "tight", "title", "today", "tonic", 
    "topic", "total", "touch", "tough", "tower", "track", "trade", "trail", "train", "trash", "treat", "trend", 
    "trial", "trick", "truly", "trust", "truth", "twice", "under", "union", "unite", "unity", "until", 
    "upper", "usual", "value", "video", "vital", "voice", "visit", "vital", "voice", "visit", "vocal", "wagon", 
    "waste", "watch", "water", "wears", "wheel", "where", "which", "while", "white", "whole", "whose", "wider", 
    "wilds", "woman", "women", "world", "worry", "wound", "woven", "write", "wrong", "wrote", "yield", "young"
];

const fourLetterWordsCaps = [
    "Able", "Acid", "Aged", "Also", "Area", "Army", "Away", "Baby", "Back", "Ball", "Band", "Bank", "Base", 
    "Bath", "Bear",
    "Beat", "Been", "Bell", "Belt", "Best", "Bill", "Bird", "Blow", "Blue", "Boat", "Body", "Bomb", "Bone", 
    "Book", "Born",
    "Boss", "Both", "Bowl", "Bulk", "Burn", "Bush", "Busy", "Call", "Calm", "Came", "Camp", "Card", "Care", 
    "Case", "Cash",
    "Cast", "Cell", "Cent", "Chat", "Chip", "City", "Club", "Coal", "Coat", "Code", "Cold", "Come", "Cook", 
    "Cool", "Cope",
    "Copy", "Core", "Cost", "Crew", "Crop", "Dark", "Data", "Date", "Dead", "Deal", "Dear", "Debt", "Deep", 
    "Desk", "Diet",
    "Disc", "Dish", "Disk", "Door", "Draw", "Drop", "Drug", "Dust", "Duty", "Each", "Earn", "Ease", "East", 
    "Easy", "Edge",
    "Else", "Even", "Ever", "Evil", "Exit", "Face", "Fact", "Fair", "Fall", "Farm", "Fast", "Fate", "Fear", 
    "Feed", "Feel",
    "Feet", "Fell", "Felt", "File", "Fill", "Film", "Find", "Fine", "Fire", "Firm", "Fish", "Five", "Flat", 
    "Flow", "Food",
    "Foot", "Form", "Fort", "Four", "Free", "From", "Fuel", "Full", "Fund", "Gain", "Game", "Gate", "Gear", 
    "Gene", "Gift",
    "Girl", "Give", "Glad", "Goal", "Gold", "Good", "Gray", "Grow", "Hair", "Half", "Hand", "Hang", "Hard", 
    "Have", "Head",
    "Hear", "Heat", "Help", "Here", "High", "Hold", "Home", "Hope", "Host", "Hour", "Huge", "Hunt", "Hurt", 
    "Idea", "Inch",
    "Into", "Iron", "Item", "Join", "Jump", "Jury", "Just", "Keep", "Kick", "Kill", "Kind", "King", "Knee", 
    "Know", "Land",
    "Last", "Late", "Lead", "Leaf", "Lean", "Left", "Less", "Life", "Lift", "Like", "Line", "Link", "List", 
    "Live", "Load",
    "Loan", "Lock", "Long", "Look", "Lose", "Loss", "Love", "Luck", "Main", "Make", "Male", "Many", "Mark", 
    "Mass", "Meal",
    "Mean", "Meet", "Menu", "Mere", "Mild", "Mile", "Milk", "Mill", "Mind", "Mine", "Miss", "Mode", "Mood", 
    "Moon", "More",
    "Most", "Move", "Much", "Must", "Name", "Near", "Neck", "Need", "News", "Next", "Nice", "Nine", "None", 
    "Nose", "Note",
    "Okay", "Once", "Only", "Onto", "Open", "Oral", "Over", "Pace", "Pack", "Page", "Pain", "Pair", "Pale", 
    "Park", "Part",
    "Pass", "Past", "Path", "Peak", "Pick", "Pink", "Plan", "Play", "Plot", "Plus", "Pool", "Port", "Post", 
    "Pour", "Pull",
    "Pure", "Push", "Race", "Rail", "Rain", "Rank", "Rare", "Rate", "Read", "Real", "Rear", "Rely", "Rent", 
    "Rest", "Rich",
    "Ride", "Ring", "Rise", "Risk", "Road", "Rock", "Role", "Roll", "Roof", "Room", "Root", "Rope", "Rose", 
    "Rule", "Rush",
    "Safe", "Said", "Sale", "Salt", "Same", "Sand", "Save", "Seat", "Seed", "Seek", "Seem", "Self", "Sell", 
    "Send", "Sent",
    "Ship", "Shop", "Shot", "Show", "Shut", "Sick", "Side", "Sign", "Silk", "Sing", "Sink", "Site", "Size", 
    "Skin", "Slip",
    "Slow", "Snow", "Soft", "Soil", "Sold", "Sole", "Some", "Song", "Soon", "Sort", "Soul", "Spot", "Star", 
    "Stay", "Step",
    "Stop", "Such", "Suit", "Sure", "Take", "Talk", "Tall", "Tank", "Tape", "Task", "Team", "Tell", "Term", 
    "Test", "Text",
    "Than", "That", "Them", "Then", "They", "Thin", "This", "Thus", "Till", "Time", "Tiny", "Told", "Toll", 
    "Tone", "Tool",
    "Tour", "Town", "Tree", "Trip", "True", "Turn", "Type", "Unit", "Upon", "Used", "User", "Vary", "Vast", 
    "Very", "View",
    "Vote", "Wait", "Wake", "Walk", "Wall", "Want", "Warm", "Warn", "Wash", "Wave", "Weak", "Wear", "Week", 
    "Well", "Went",
    "Were", "West", "What", "When", "Whom", "Wide", "Wife", "Wild", "Will", "Wind", "Wine", "Wing", "Wire", 
    "Wise", "Wish",
    "With", "Wood", "Word", "Worn", "Yard", "Yeah", "Year", "Yell", "Your", "Zero", "Zone"
];

const fiveLetterWordsCaps = [
    "About", "Above", "Actor", "Acute", "Admit", "Adopt", "Adult", "After", "Again", "Agent", "Agree", "Ahead", 
    "Alarm", "Album", "Alert",
    "Alike", "Alive", "Allow", "Alone", "Along", "Alter", "Among", "Anger", "Angle", "Angry", "Ankle", "Apart", 
    "Apple", "Apply", "Arena",
    "Argue", "Arise", "Array", "Aside", "Asset", "Audio", "Audit", "Avoid", "Award", "Aware", "Basic", "Basis", 
    "Beach", "Began", "Begin",
    "Begun", "Being", "Below", "Bench", "Billy", "Birth", "Black", "Blade", "Blame", "Blank", "Blast", "Blend", 
    "Bless", "Blind", "Block",
    "Blood", "Board", "Boost", "Booty", "Bored", "Bound", "Brain", "Brave", "Bread", "Break", "Breed", "Brick", 
    "Brief", "Bring", "Broad",
    "Brown", "Brush", "Bunch", "Buyer", "Cabin", "Cable", "Candy", "Carry", "Chain", "Chair", "Chart", "Chase", 
    "Cheap", "Check", "Cheek",
    "Cheer", "Chief", "Child", "Chose", "Civil", "Claim", "Class", "Clean", "Clear", "Clerk", "Click", "Clock", 
    "Close", "Cloth", "Cloud",
    "Coach", "Coast", "Could", "Count", "Court", "Cover", "Craft", "Crash", "Crawl", "Cream", "Crime", "Cross", 
    "Crowd", "Crown", "Curve",
    "Cycle", "Daily", "Dance", "Dated", "Death", "Debit", "Debut", "Decay", "Decor", "Delay", "Depth", "Diary", 
    "Dirty", "Diver", "Doing",
    "Doubt", "Draft", "Dream", "Dress", "Drink", "Drive", "Drove", "Drown", "Eager", "Early", "Earth", "Eight", 
    "Elder", "Elect", "Elite",
    "Empty", "Enemy", "Enjoy", "Enter", "Entry", "Equal", "Error", "Essay", "Event", "Every", "Exact", "Exist", 
    "Extra", "Faith", "False",
    "Fault", "Favor", "Fifth", "Fight", "Final", "First", "Fixed", "Flash", "Fleet", "Flesh", "Flight", "Float", 
    "Floor", "Flour", "Focus",
    "Force", "Frame", "Frank", "Fraud", "Fresh", "Front", "Fruit", "Fully", "Funny", "Giant", "Given", "Glass", 
    "Globe", "Going", "Grace",
    "Grade", "Grand", "Grant", "Grass", "Great", "Green", "Gross", "Group", "Grown", "Guard", "Guest", "Guide", 
    "Habit", "Happy", "Harry",
    "Heart", "Heavy", "Hence", "Horse", "Hotel", "House", "Human", "Ideal", "Index", "Inner", "Input", "Issue", 
    "Joint", "Jones", "Judge",
    "Known", "Label", "Large", "Laser", "Later", "Laugh", "Layer", "Learn", "Least", "Leave", "Legal", "Lemon", 
    "Level", "Light", "Limit",
    "Lunch", "Major", "Maker", "March", "Mario", "Match", "Mayor", "Meant", "Media", "Metal", "Might", "Minor", 
    "Model", "Money", "Month",
    "Moral", "Motor", "Mount", "Mouse", "Mouth", "Movie", "Music", "Needs", "Never", "Newly", "Night", "Noise", 
    "North", "Novel", "Nurse",
    "Occur", "Ocean", "Offer", "Often", "Order", "Other", "Owner", "Panel", "Paper", "Party", "Peace", "Peter", 
    "Phase", "Phone", "Piece",
    "Pilot", "Pitch", "Place", "Plain", "Plane", "Plant", "Plate", "Point", "Pound", "Power", "Press", "Price", 
    "Pride", "Prime", "Print",
    "Prior", "Prize", "Proof", "Proud", "Prove", "Queen", "Quick", "Quiet", "Quite", "Radio", "Raise", "Range", 
    "Rapid", "Ratio", "Reach",
    "React", "Ready", "Refer", "Right", "Rival", "River", "Round", "Route", "Royal", "Rugby", "Rural", "Scale", 
    "Scene", "Scope", "Score",
    "Sense", "Serve", "Seven", "Shall", "Shape", "Share", "Sharp", "Sheet", "Shelf", "Shell", "Shift", "Shirt", 
    "Shock", "Shoot", "Short",
    "Shout", "Since", "Sixth", "Sixty", "Skill", "Sleep", "Slide", "Small", "Smart", "Smile", "Smith", "Smoke", 
    "Solid", "Solve", "Sorry",
    "Sound", "South", "Space", "Spare", "Speak", "Speed", "Spend", "Spite", "Split", "Sport", "Squad", "Staff", 
    "Stage", "Stand", "Start",
    "State", "Steam", "Steel", "Stick", "Still", "Stock", "Stone", "Stood", "Store", "Storm", "Story", "Strip", 
    "Stuck", "Study", "Stuff",
    "Style", "Sugar", "Suite", "Super", "Sweet", "Table", "Taken", "Taste", "Teach", "Teeth", "Terry", "Thank", 
    "Their", "Theme", "There",
    "These", "Thick", "Thing", "Think", "Third", "Those", "Three", "Threw", "Throw", "Tight", "Times", "Tired", 
    "Title", "Today", "Topic",
    "Total", "Touch", "Tough", "Tower", "Track", "Trade", "Train", "Trend", "Trial", "Tried", "Tries", "Trust", 
    "Truth", "Twice", "Under",
    "Undue", "Union", "Unity", "Until", "Upper", "Upset", "Urban", "Usage", "Usual", "Valid", "Value", "Video", 
    "Visit", "Vital", "Voice",
    "Wages", "Waste", "Watch", "Water", "Waved", "Waxes", "Wears", "Weary", "Wedge", "Whale", "Wheat", "Wheez", 
    "Whiff", "Whims", "Whips",
    "White", "Whole", "Widen", "Widow", "Width", "Wield", "Wight", "Wimps", "Wimpy", "Wings", "Winks", "Wires", 
    "Wiser", "Wiser", "Withe",
    "Witly", "Wobbs", "Wobds", "Woody", "Wooer", "Wooty", "Works", "World", "Worry", "Worse", "Worst", "Worwy", 
    "Wovbs", "Wrack", "Wrath",
    "Wribs", "Wrile", "Wrily", "Wrist", "Write", "Writh", "Writt", "Wroly", "Wroth", "Wubbs", "Wubds", "Wudly", 
    "Wunly", "Wwral", "Xanbs",
    "Xaxis", "Xeras", "Xerys", "Xonas", "Xonee", "Xoney", "Xorke", "Xorns", "Xorry", "Xunts", "Yards", "Years", 
    "Yells", "Yellow", "Yests",
    "Yield", "Yokel", "Yould", "Young", "Yours", "Youse", "Yovly", "Zaxes", "Zebra", "Zoras", "Zorra", "Zorry", 
    "Zubbs", "Zunts", "Zuphs"
];


const sixLetterWords = [
    "abroad", "absent", "accept", "access", "across", "acting", "action", "active", "actual", "admire",
    "advice", "advise", "affair", "affect", "afford", "afraid", "agency", "agenda", "almost", "always",
    "amount", "animal", "annual", "answer", "anyone", "anyway", "appeal", "appear", "around", "arrive",
    "artist", "aspect", "assess", "assist", "assume", "assure", "attach", "attack", "attend", "author",
    "autumn", "avenue", "backed", "barely", "barrel", "basket", "battle", "beauty", "became", "become",
    "before", "behalf", "behave", "behind", "belief", "belong", "beside", "better", "beyond", "bishop",
    "border", "borrow", "bottle", "bottom", "bought", "branch", "breath", "bridge", "bright", "broken",
    "budget", "burden", "bureau", "button", "camera", "cancel", "cancer", "cannot", "carbon", "career",
    "castle", "casual", "caught", "center", "chance", "change", "charge", "choice", "choose", "church",
    "circle", "client", "closed", "closer", "coffee", "collar", "colony", "colour", "combat", "comedy",
    "coming", "commit", "common", "comply", "convey", "copper", "corner", "costly", "county", "couple",
    "course", "cousin", "create", "credit", "crisis", "critic", "custom", "damage", "danger", "dealer",
    "debate", "decade", "decent", "decide", "defeat", "defend", "define", "degree", "demand", "depend",
    "deploy", "derive", "desert", "design", "desire", "detail", "detect", "device", "devote", "differ",
    "dinner", "direct", "divide", "doctor", "dollar", "domain", "donate", "double", "dragon", "drawer",
    "driven", "driver", "during", "easily", "editor", "effect", "effort", "eighth", "either", "eleven",
    "emerge", "empire", "employ", "enable", "ending", "endure", "energy", "engine", "enough", "enroll",
    "ensure", "entire", "entity", "equity", "escape", "estate", "ethnic", "evolve", "exceed", "except",
    "excess", "excise", "excuse", "exempt", "exodus", "exotic", "expand", "expect", "expert", "expire",
    "export", "expose", "extend", "extent", "fabric", "facial", "facing", "factor", "failed", "fairly",
    "fallen", "family", "famous", "farmer", "father", "favour", "fellow", "female", "fierce", "figure",
    "filing", "filter", "finale", "finely", "finger", "finish", "finite", "fiscal", "fisher", "flight",
    "flower", "follow", "forced", "forest", "forget", "formal", "format", "former", "fossil", "foster",
    "fought", "fourth", "freeze", "friend", "fringe", "frozen", "future", "galaxy", "gallon", "gamble",
    "garden", "gender", "genius", "gentle", "german", "gifted", "ginger", "global", "golden", "google",
    "gospel", "gossip", "govern", "grader", "gravel", "ground", "growth", "guilty", "guitar", "hammer",
    "handed", "handle", "happen", "harbor", "hardly", "hassle", "hatred", "headed", "health", "heated",
    "heaven", "height", "helmet", "herald", "hereby", "herein", "heroic", "hidden", "holder", "hollow",
    "honest", "honour", "hooked", "horror", "humble", "hunger", "hungry", "hunter", "hurdle", "hybrid",
    "ignore", "immune", "impact", "import", "impose", "income", "indeed", "indoor", "infant", "inform",
    "injury", "inland", "insert", "inside", "insist", "insure", "intact", "intake", "intend", "intent",
    "invest", "invite", "island", "itself", "jacket", "jargon", "jersey", "jewish", "jigsaw", "jockey",
    "jungle", "junior", "keeper", "kidney", "killed", "killer", "kindly", "knight", "labour", "laptop",
    "larger", "lasted", "lately", "latest", "latter", "launch", "lawyer", "leader", "league", "leaves",
    "legacy", "legend", "lender", "length", "lesser", "lesson", "letter", "lights", "likely", "linked",
    "liquid", "listen", "little", "living", "locate", "lonely", "longer", "looked", "losing", "lounge",
    "lovely", "lovers", "loving", "luxury", "mainly", "making", "manage", "manner", "manual", "margin",
    "marine", "marked", "market", "marvel", "master", "matter", "mature", "medium", "member", "memory",
    "mental", "merely", "merger", "method", "middle", "mighty", "miners", "mining", "minute", "mirror",
    "misery", "mobile", "modern", "modest", "moment", "monday", "monkey", "months", "mostly", "mother",
    "motion", "moving", "murder", "museum", "mutual", "myself", "narrow", "nation", "native", "nature",
    "nearby", "nearly", "nights", "nobody", "normal", "notice", "notion", "number", "object", "obtain",
    "office", "offset", "online", "option", "orange", "origin", "outfit", "outlet", "output", "overly",
    "owners", "oxygen", "packed", "palace", "parent", "partly", "patent", "people", "period", "permit",
    "person", "phases", "phones", "photos", "picked", "planet", "plants", "plenty", "pocket", "police",
    "policy", "prefer", "pretty", "prince", "prison", "profit", "prompt", "proper", "public", "purely",
    "pursue", "raised", "random", "rarely", "rather", "rating", "reader", "really", "reason", "recall",
    "recent", "record", "reduce", "reform", "regard", "regime", "region", "relate", "relief", "remain",
    "remote", "remove", "repair", "repeat", "report", "rescue", "resort", "result", "retail", "retain",
    "return", "reveal", "review", "reward", "riding", "rising", "robust", "ruling", "safely", "safety",
    "salary", "sample", "saving", "saying", "scheme", "school", "screen", "search", "season", "second",
    "secret", "sector", "secure", "seeing", "select", "seller", "senior", "series", "server", "settle",
    "severe", "sexual", "should", "signal", "signed", "silent", "silver", "simple", "simply", "single",
    "sister", "slight", "smooth", "social", "solely", "sought", "source", "soviet", "speech", "spirit",
    "spoken", "spread", "spring", "square", "stable", "status", "steady", "stolen", "strain", "stream",
    "street", "stress", "strict", "strike", "string", "strong", "struck", "studio", "submit", "sudden",
    "suffer", "summer", "summit", "supply", "surely", "survey", "switch", "symbol" 
];

const sixLetterWordsCaps = [
    "Abroad", "Absent", "Accept", "Access", "Across", "Acting", "Action", "Active", "Actual", "Admire", "Advice", "Advise", "Affair", "Affect", "Afford",
    "Afraid", "Agency", "Agenda", "Almost", "Always", "Amount", "Animal", "Annual", "Answer", "Anyone", "Anyway", "Appeal", "Appear", "Around", "Arrive",
    "Artist", "Aspect", "Assess", "Assist", "Assume", "Assure", "Attach", "Attack", "Attend", "Author", "Autumn", "Avenue", "Backed", "Barely", "Barrel",
    "Basket", "Battle", "Beauty", "Became", "Become", "Before", "Behalf", "Behave", "Behind", "Belief", "Belong", "Beside", "Better", "Beyond", "Bishop",
    "Border", "Borrow", "Bottle", "Bottom", "Bought", "Branch", "Breath", "Bridge", "Bright", "Broken", "Budget", "Burden", "Bureau", "Button", "Camera",
    "Cancel", "Cancer", "Cannot", "Carbon", "Career", "Castle", "Casual", "Caught", "Center", "Chance", "Change", "Charge", "Choice", "Choose", "Church",
    "Circle", "Client", "Closed", "Closer", "Coffee", "Collar", "Colony", "Colour", "Combat", "Comedy", "Coming", "Commit", "Common", "Comply", "Convey",
    "Copper", "Corner", "Costly", "County", "Couple", "Course", "Cousin", "Create", "Credit", "Crisis", "Critic", "Custom", "Damage", "Danger", "Dealer",
    "Debate", "Decade", "Decent", "Decide", "Defeat", "Defend", "Define", "Degree", "Demand", "Depend", "Deploy", "Derive", "Desert", "Design", "Desire",
    "Detail", "Detect", "Device", "Devote", "Differ", "Dinner", "Direct", "Divide", "Doctor", "Dollar", "Domain", "Donate", "Double", "Dragon", "Drawer",
    "Driven", "Driver", "During", "Easily", "Editor", "Effect", "Effort", "Eighth", "Either", "Eleven", "Emerge", "Empire", "Employ", "Enable", "Ending",
    "Endure", "Energy", "Engine", "Enough", "Enroll", "Ensure", "Entire", "Entity", "Equity", "Escape", "Estate", "Ethnic", "Evolve", "Exceed", "Except", 
    "Excess", "Excise", "Excuse", "Exempt", "Exodus", "Exotic", "Expand", "Expect", "Expert", "Expire", "Export", "Expose", "Extend", "Extent", "Fabric",
    "Facial", "Facing", "Factor", "Failed", "Fairly", "Fallen", "Family", "Famous", "Farmer", "Father", "Favour", "Fellow", "Female", "Fierce", "Figure",
    "Filing", "Filter", "Finale", "Finely", "Finger", "Finish", "Finite", "Fiscal", "Fisher", "Flight", "Flower", "Follow", "Forced", "Forest", "Forget",
    "Formal", "Format", "Former", "Fossil", "Foster", "Fought", "Fourth", "Freeze", "Friend", "Fringe", "Frozen", "Future", "Galaxy", "Gallon", "Gamble",
    "Garden", "Gender", "Genius", "Gentle", "German", "Gifted", "Ginger", "Global", "Golden", "Google", "Gospel", "Gossip", "Govern", "Grader", "Gravel",
    "Ground", "Growth", "Guilty", "Guitar", "Hammer", "Handed", "Handle", "Happen", "Harbor", "Hardly", "Hassle", "Hatred", "Headed", "Health", "Heated", 
    "Heaven", "Height", "Helmet", "Herald", "Hereby", "Herein", "Heroic", "Hidden", "Holder", "Hollow", "Honest", "Honour", "Hooked", "Horror", "Humble", 
    "Hunger", "Hungry", "Hunter", "Hurdle", "Hybrid", "Ignore", "Immune", "Impact", "Import", "Impose", "Income", "Indeed", "Indoor", "Infant", "Inform", 
    "Injury", "Inland", "Insert", "Inside", "Insist", "Insure", "Intact", "Intake", "Intend", "Intent", "Invest", "Invite", "Island", "Itself", "Jacket",
    "Jargon", "Jersey", "Jewish", "Jigsaw", "Jockey", "Jungle", "Junior", "Keeper", "Kidney", "Killed", "Killer", "Kindly", "Knight", "Labour", "Laptop",
    "Larger", "Lasted", "Lately", "Latest", "Latter", "Launch", "Lawyer", "Leader", "League", "Leaves", "Legacy", "Legend", "Lender", "Length", "Lesser",
    "Lesson", "Letter", "Lights", "Likely", "Linked", "Liquid", "Listen", "Little", "Living", "Locate", "Lonely", "Longer", "Looked", "Losing", "Lounge",
    "Lovely", "Lovers", "Loving", "Luxury", "Mainly", "Making", "Manage", "Manner", "Manual", "Margin", "Marine", "Marked", "Market", "Marvel", "Master",
    "Matter", "Mature", "Medium", "Member", "Memory", "Mental", "Merely", "Merger", "Method", "Middle", "Mighty", "Miners", "Mining", "Minute", "Mirror",
    "Misery", "Mobile", "Modern", "Modest", "Moment", "Monday", "Monkey", "Months", "Mostly", "Mother", "Motion", "Moving", "Murder", "Museum", "Mutual",
    "Myself", "Narrow", "Nation", "Native", "Nature", "Nearby", "Nearly", "Nights", "Nobody", "Normal", "Notice", "Notion", "Number", "Object", "Obtain",
    "Office", "Offset", "Online", "Option", "Orange", "Origin", "Outfit", "Outlet", "Output", "Overly", "Owners", "Oxygen", "Packed", "Palace", "Parent",
    "Partly", "Patent", "People", "Period", "Permit", "Person", "Phases", "Phones", "Photos", "Picked", "Planet", "Plants", "Plenty", "Pocket", "Police",
    "Policy", "Prefer", "Pretty", "Prince", "Prison", "Profit", "Prompt", "Proper", "Public", "Purely", "Pursue", "Raised", "Random", "Rarely", "Rather",
    "Rating", "Reader", "Really", "Reason", "Recall", "Recent", "Record", "Reduce", "Reform", "Regard", "Regime", "Region", "Relate", "Relief", "Remain",
    "Remote", "Remove", "Repair", "Repeat", "Report", "Rescue", "Resort", "Result", "Retail", "Retain", "Return", "Reveal", "Review", "Reward", "Riding",
    "Rising", "Robust", "Ruling", "Safely", "Safety", "Salary", "Sample", "Saving", "Saying", "Scheme", "School", "Screen", "Search", "Season", "Second",
    "Secret", "Sector", "Secure", "Seeing", "Select", "Seller", "Senior", "Series", "Server", "Settle", "Severe", "Sexual", "Should", "Signal", "Signed",
    "Silent", "Silver", "Simple", "Simply", "Single", "Sister", "Slight", "Smooth", "Social", "Solely", "Sought", "Source", "Soviet", "Speech", "Spirit",
    "Spoken", "Spread", "Spring", "Square", "Stable", "Status", "Steady", "Stolen", "Strain", "Stream", "Street", "Stress", "Strict", "Strike", "String",
    "Strong", "Struck", "Studio", "Submit", "Sudden", "Suffer", "Summer", "Summit", "Supply", "Surely", "Survey", "Switch", "Symbol"
];

const sevenLetterWords = [
    "abandon", "ability", "absence", "academy", "account", "accused", "achieve", "acquire", "address", "advance",
    "adverse", "advised", "adviser", "against", "airline", "airport", "alcohol", "alleged", "already", "analyst",
    "ancient", "another", "anxiety", "anxious", "anybody", "applied", "arrange", "arrival", "article", "assault",
    "assumed", "assured", "attempt", "attract", "auction", "average", "backing", "balance", "banking", "barrier",
    "battery", "bearing", "beating", "because", "bedroom", "believe", "beneath", "benefit", "besides", "between",
    "billion", "binding", "brother", "brought", "burning", "cabinet", "caliber", "calling", "capable", "capital",
    "captain", "caption", "capture", "careful", "carrier", "caution", "ceiling", "central", "century", "certain",
    "chamber", "channel", "chapter", "charity", "charter", "checked", "chicken", "chronic", "circuit", "citizen",
    "clarity", "classic", "climate", "closing", "closure", "clothes", "collect", "college", "combine", "comfort",
    "command", "comment", "compact", "company", "compare", "compete", "complex", "concept", "concern", "concert",
    "conduct", "confirm", "connect", "consent", "consist", "contact", "contain", "content", "contest", "context",
    "control", "convert", "correct", "council", "counsel", "counter", "country", "crucial", "crystal", "culture",
    "current", "cutting", "dealing", "decided", "decline", "default", "defence", "deficit", "deliver", "density",
    "deposit", "desktop", "despite", "destroy", "develop", "devoted", "diamond", "digital", "discuss", "disease",
    "display", "dispute", "distant", "diverse", "divided", "drawing", "driving", "dynamic", "eastern", "economy",
    "edition", "elderly", "element", "engaged", "enhance", "essence", "evening", "evident", "exactly", "examine",
    "example", "excited", "exclude", "exhibit", "expense", "explain", "explore", "express", "extreme", "factory",
    "faculty", "failure", "fashion", "feature", "federal", "feeling", "fiction", "fifteen", "filling", "finance",
    "finding", "fishing", "fitness", "foreign", "forever", "formula", "fortune", "forward", "founder", "freedom",
    "further", "gallery", "gateway", "general", "genetic", "genuine", "gesture", "greater", "hanging", "heading",
    "healthy", "hearing", "heavily", "helpful", "helping", "herself", "highway", "himself", "history", "holding",
    "holiday", "housing", "however", "hundred", "husband", "illegal", "illness", "imagine", "imaging", "improve",
    "include", "initial", "inquiry", "insight", "install", "instant", "instead", "intense", "interim", "involve",
    "jointly", "journal", "journey", "justice", "justify", "keeping", "kitchen", "knowing", "landing", "largely",
    "lasting", "leading", "learned", "leisure", "liberal", "liberty", "library", "license", "limited", "listing",
    "logical", "loyalty", "machine", "manager", "married", "massive", "maximum", "meaning", "measure", "medical",
    "meeting", "mention", "message", "million", "mineral", "minimal", "minimum", "missing", "mission", "mistake",
    "mixture", "monitor", "monthly", "morning", "musical", "mystery", "natural", "neither", "nervous", "network",
    "neutral", "notable", "nothing", "nowhere", "nuclear", "nursing", "obvious", "offense", "officer", "ongoing",
    "opening", "operate", "opinion", "optical", "organic", "outcome", "outdoor", "outlook", "outside", "overall",
    "package", "painted", "parking", "partial", "partner", "passage", "passing", "passion", "patient", "pattern",
    "payable", "payment", "penalty", "pending", "pension", "percent", "perfect", "perform", "perhaps", "phoenix",
    "picking", "picture", "pioneer", "plastic", "pointed", "popular", "portion", "poverty", "precise", "predict",
    "premier", "premium", "prepare", "present", "prevent", "primary", "printer", "privacy", "private", "problem",
    "proceed", "process", "produce", "product", "profile", "program", "project", "promise", "promote", "protect",
    "protein", "protest", "provide", "publish", "purpose", "pursuit", "qualify", "quality", "quarter", "radical",
    "railway", "readily", "reading", "reality", "realize", "receipt", "receive", "recover", "reflect", "reform",
    "refugee", "regimen", "regular", "related", "release", "remains", "removal", "replace", "request", "require",
    "reserve", "resolve", "respect", "respond", "restore", "retired", "revenue", "reverse", "rollout", "routine",
    "running", "satisfy", "science", "section", "segment", "serious", "service", "serving", "session", "setting",
    "seventh", "several", "shortly", "showing", "silence", "silicon", "similar", "sitting", "sixteen", "skilled",
    "smoking", "society", "somehow", "someone", "speaker", "special", "species", "sponsor", "station", "storage",
    "strange", "stretch", "student", "studied", "subject", "succeed", "success", "suggest", "summary", "support",
    "suppose", "supreme", "surface", "surgery", "surplus", "survive", "suspect", "sustain", "teacher", "telecom",
    "telling", "tension", "theatre", "therapy", "thereby", "thought", "through", "tonight", "totally", "tourist",
    "trading", "traffic", "tragedy", "trainer", "transit", "treated", "trouble", "turning", "typical", "uniform",
    "unknown", "unusual", "upgrade", "upscale", "utility", "variety", "various", "vehicle", "venture", "version",
    "veteran", "victory", "viewing", "village", "violent", "virtual", "visible", "waiting", "walking", "wanting",
    "warning", "warrant", "wearing", "weather", "webcast", "website", "wedding", "weekend", "welcome", "welfare",
    "western", "whereas", "whereby", "whether", "willing", "winning", "without", "witness", "working", "writing",
    "written", "younger"
];

const sevenLetterWordsCaps = [
    "Abandon", "Ability", "Absence", "Academy", "Account", "Accused", "Achieve", "Acquire", "Address", "Advance", "Adverse", "Advised", "Adviser", "Against", "Airline",
    "Airport", "Alcohol", "Alleged", "Already", "Analyst", "Ancient", "Another", "Anxiety", "Anxious", "Anybody", "Applied", "Arrange", "Arrival", "Article", "Assault",
    "Assumed", "Assured", "Attempt", "Attract", "Auction", "Average", "Backing", "Balance", "Banking", "Barrier", "Battery", "Bearing", "Beating", "Because", "Bedroom",
    "Believe", "Beneath", "Benefit", "Besides", "Between", "Billion", "Binding", "Brother", "Brought", "Burning", "Cabinet", "Caliber", "Calling", "Capable", "Capital",
    "Captain", "Caption", "Capture", "Careful", "Carrier", "Caution", "Ceiling", "Central", "Century", "Certain", "Chamber", "Channel", "Chapter", "Charity", "Charter",
    "Checked", "Chicken", "Chronic", "Circuit", "Citizen", "Clarity", "Classic", "Climate", "Closing", "Closure", "Clothes", "Collect", "College", "Combine", "Comfort",
    "Command", "Comment", "Compact", "Company", "Compare", "Compete", "Complex", "Concept", "Concern", "Concert", "Conduct", "Confirm", "Connect", "Consent", "Consist",
    "Contact", "Contain", "Content", "Contest", "Context", "Control", "Convert", "Correct", "Council", "Counsel", "Counter", "Country", "Crucial", "Crystal", "Culture",
    "Current", "Cutting", "Dealing", "Decided", "Decline", "Default", "Defence", "Deficit", "Deliver", "Density", "Deposit", "Desktop", "Despite", "Destroy", "Develop",
    "Devoted", "Diamond", "Digital", "Discuss", "Disease", "Display", "Dispute", "Distant", "Diverse", "Divided", "Drawing", "Driving", "Dynamic", "Eastern", "Economy",
    "Edition", "Elderly", "Element", "Engaged", "Enhance", "Essence", "Evening", "Evident", "Exactly", "Examine", "Example", "Excited", "Exclude", "Exhibit", "Expense",
    "Explain", "Explore", "Express", "Extreme", "Factory", "Faculty", "Failure", "Fashion", "Feature", "Federal", "Feeling", "Fiction", "Fifteen", "Filling", "Finance",
    "Finding", "Fishing", "Fitness", "Foreign", "Forever", "Formula", "Fortune", "Forward", "Founder", "Freedom", "Further", "Gallery", "Gateway", "General", "Genetic",
    "Genuine", "Gesture", "Greater", "Hanging", "Heading", "Healthy", "Hearing", "Heavily", "Helpful", "Helping", "Herself", "Highway", "Himself", "History", "Holding",
    "Holiday", "Housing", "However", "Hundred", "Husband", "Illegal", "Illness", "Imagine", "Imaging", "Improve", "Include", "Initial", "Inquiry", "Insight", "Install",
    "Instant", "Instead", "Intense", "Interim", "Involve", "Jointly", "Journal", "Journey", "Justice", "Justify", "Keeping", "Kitchen", "Knowing", "Landing", "Largely",
    "Lasting", "Leading", "Learned", "Leisure", "Liberal", "Liberty", "Library", "License", "Limited", "Listing", "Logical", "Loyalty", "Machine", "Manager", "Married",
    "Massive", "Maximum", "Meaning", "Measure", "Medical", "Meeting", "Mention", "Message", "Million", "Mineral", "Minimal", "Minimum", "Missing", "Mission", "Mistake",
    "Mixture", "Monitor", "Monthly", "Morning", "Musical", "Mystery", "Natural", "Neither", "Nervous", "Network", "Neutral", "Notable", "Nothing", "Nowhere", "Nuclear",
    "Nursing", "Obvious", "Offense", "Officer", "Ongoing", "Opening", "Operate", "Opinion", "Optical", "Organic", "Outcome", "Outdoor", "Outlook", "Outside", "Overall",
    "Package", "Painted", "Parking", "Partial", "Partner", "Passage", "Passing", "Passion", "Patient", "Pattern", "Payable", "Payment", "Penalty", "Pending", "Pension",
    "Percent", "Perfect", "Perform", "Perhaps", "Phoenix", "Picking", "Picture", "Pioneer", "Plastic", "Pointed", "Popular", "Portion", "Poverty", "Precise", "Predict",
    "Premier", "Premium", "Prepare", "Present", "Prevent", "Primary", "Printer", "Privacy", "Private", "Problem", "Proceed", "Process", "Produce", "Product", "Profile",
    "Program", "Project", "Promise", "Promote", "Protect", "Protein", "Protest", "Provide", "Publish", "Purpose", "Pursuit", "Qualify", "Quality", "Quarter", "Radical",
    "Railway", "Readily", "Reading", "Reality", "Realize", "Receipt", "Receive", "Recover", "Reflect", "Reform", "Refugee", "Regimen", "Regular", "Related", "Release",
    "Remains", "Removal", "Replace", "Request", "Require", "Reserve", "Resolve", "Respect", "Respond", "Restore", "Retired", "Revenue", "Reverse", "Rollout", "Routine",
    "Running", "Satisfy", "Science", "Section", "Segment", "Serious", "Service", "Serving", "Session", "Setting", "Seventh", "Several", "Shortly", "Showing", "Silence",
    "Silicon", "Similar", "Sitting", "Sixteen", "Skilled", "Smoking", "Society", "Somehow", "Someone", "Speaker", "Special", "Species", "Sponsor", "Station", "Storage",
    "Strange", "Stretch", "Student", "Studied", "Subject", "Succeed", "Success", "Suggest", "Summary", "Support", "Suppose", "Supreme", "Surface", "Surgery", "Surplus",
    "Survive", "Suspect", "Sustain", "Teacher", "Telecom", "Telling", "Tension", "Theatre", "Therapy", "Thereby", "Thought", "Through", "Tonight", "Totally", "Tourist",
    "Trading", "Traffic", "Tragedy", "Trainer", "Transit", "Treated", "Trouble", "Turning", "Typical", "Uniform", "Unknown", "Unusual", "Upgrade", "Upscale", "Utility",
    "Variety", "Various", "Vehicle", "Venture", "Version", "Veteran", "Victory", "Viewing", "Village", "Violent", "Virtual", "Visible", "Waiting", "Walking", "Wanting",
    "Warning", "Warrant", "Wearing", "Weather", "Webcast", "Website", "Wedding", "Weekend", "Welcome", "Welfare", "Western", "Whereas", "Whereby", "Whether", "Willing",
    "Winning", "Without", "Witness", "Working", "Writing", "Written", "Younger"
];


const eightLetterWords = [
    "abandoned", "absolute", "academic", "accepted", "accident", "accuracy", "accurate", "achieved", 
    "acquired", "activity", "actually", "addition", "adequate", "adjacent", "adjusted", "advanced", "advisory", 
    "affected", "aircraft", "alliance", "although", "aluminum", "analysis", "announce", "anything", 
    "apparent", "approach", "approval", "argument", "artistic", "assembly", "assuming", "athletic", 
    "attached", "attitude", "attorney", "audience", "autonomy", "aviation", "bachelor", "bacteria", 
    "baseball", "bathroom", "becoming", "benefits", "birthday", "boundary", "breaking", "breeding", 
    "building", "bulletin", "business", "calendar", "campaign", "capacity", "casualty", "catching", 
    "category", "ceremony", "chairman", "champion", "chemical", "children", "circular", "civilian", 
    "clearing", "clinical", "clothing", "collapse", "colonial", "colorful", "commence", "commerce", 
    "complain", "complete", "composed", "compound", "compress", "computer", "conclude", "concrete", 
    "conflict", "confused", "congress", "consider", "constant", "consumer", "continue", "contract", 
    "contrast", "convince", "corridor", "coverage", "creating", "creation", "creative", "criminal", 
    "critical", "crossing", "cultural", "customer", "database", "daughter", "daylight", "deadline", 
    "deciding", "decision", "decrease", "deferred", "delegate", "delicate", "delivery", "describe", 
    "designer", "detailed", "detector", "determine", "develops", "diagnose", "dialogue", "diameter", 
    "directly", "director", "disabled", "disaster", "disclose", "discount", "discover", "discrete", 
    "dispatch", "disposal", "distance", "distinct", "district", "dividend", "division", "doctrine", 
    "document", "domestic", "dominant", "dominate", "doubtful", "dramatic", "dressing", "dropping", 
    "duration", "dynamics", "earnings", "economic", "educated", "effected", "election", "electric", 
    "eligible", "emerging", "emphasis", "employee", "endeavor", "engaging", "engineer", "enormous", 
    "entering", "entirely", "entrance", "envelope", "equality", "equation", "estimate", "evaluate", 
    "evenings", "evidence", "exchange", "exciting", "exercise", "explicit", "exposure", "extended", 
    "external", "facility", "familiar", "featured", "feedback", "festival", "finished", "firewall", 
    "flagship", "flexible", "floating", "football", "foothill", "forecast", "forehead", "formerly", 
    "fourteen", "fraction", "fragment", "franklin", "frequent", "friendly", "frontier", "function", 
    "generate", "generous", "genomics", "governor", "graduate", "graphics", "grounded", "guidance", 
    "handling", "hardware", "heritage", "hesitate", "historic", "hospital", "humanity", "humidity", 
    "identity", "ideology", "imperial", "incident", "included", "increase", "indicate", "indirect", 
    "industry", "informal", "informed", "inherent", "initiate", "innocent", "inspired", "instance", 
    "instruct", "integral", "intended", "interact", "interest", "interior", "internal", "interval", 
    "intimate", "intranet", "invasion", "involved", "isolated", "judgment", "junction", "juvenile", 
    "keyboard", "laughter", "learning", "lecturer", "leftover", "lifetime", "lighting", "likewise", 
    "limiting", "literacy", "location", "lifetime", "magazine", "magnetic", "maintain", "majority", 
    "marginal", "maritime", "marketing", "marriage", "material", "maturity", "maximize", "meantime", 
    "measured", "medicine", "medieval", "membrane", "merchant", "midnight", "military", "minimize", 
    "minister", "ministry", "minority", "mobility", "modeling", "moderate", "momentum", "monetary", 
    "monopoly", "moreover", "motivate", "mountain", "movement", "multiple", "national", "negative", 
    "neighbor", "neutrino", "nominate", "northern", "notation", "novelist", "numerous", "observer", 
    "occasion", "offender", "offering", "official", "offspring", "operator", "opponent", "opposite", 
    "optimism", "optional", "ordering", "ordinary", "organize", "original", "overcome", "overhead", 
    "overlook", "overseas", "overview", "painting", "parallel", "parental", "patience", "peaceful", 
    "periodic", "personal", "persuade", "petition", "physical", "pipeline", "platform", "pleasant", 
    "pleasure", "plumbing", "pointing", "policies", "politics", "portable", "position", "positive", 
    "possible", "possibly", "potential", "practice", "precious", "presence", "preserve", "pressure", 
    "previous", "priority", "probably", "producer", "profound", "progress", "property", "proposal", 
    "prospect", "protocol", "provided", "provider", "province", "publicly", "purchase", "pursuing", 
    "quantity", "question", "rational", "reaction", "received", "recently", "recovery", "regional", 
    "register", "relation", "relative", "relevant", "reliable", "relieved", "religion", "remember", 
    "reporter", "republic", "required", "research", "reserved", "resident", "resolved", "resource", 
    "response", "restrict", "revision", "rigorous", "romantic", "sampling", "scenario", "schedule", 
    "sciences", "scrutiny", "seasonal", "secondary", "security", "sensible", "sentence", "separate", 
    "sequence", "sergeant", "shipping", "shortage", "shoulder", "simplify", "situated", "software", 
    "solution", "somebody", "somewhat", "southern", "speaking", "specific", "spectrum", "sporting", 
    "standard", "standing", "standout", "sterling", "straight", "strategy", "strength", "striking", 
    "struggle", "stunning", "suburban", "suitable", "superior", "supplier", "supposed", "surgical", 
    "surprise", "survival", "sweeping", "swimming", "symbolic", "sympathy", "syndrome", "tactical", 
    "tailored", "takeover", "taxation", "teaching", "terminal", "terrific", "textbook", "textiles", 
    "thinking", "thorough", "threaten", "together", "tomorrow", "tracking", "training", "transfer", 
    "translate", "traveled", "triangle", "ultimate", "umbrella", "universe", "unlawful", "unlisted", 
    "unlikely", "unmanned", "unsigned", "unwanted", "upgrade", "upstairs", "vacation", "valuable", 
    "variable", "vertical", "violence", "volatile", "volunteer", "wardrobe", "warranty", "weakness", 
    "widespread", "wildlife", "withdraw", "withheld", "workshop", "worldwide", "yourself", "zealotry"
];


const eightLetterWordsCaps = [
    "Abandoned", "Absolute", "Academic", "Accepted", "Accident", "Accuracy", "Accurate", "Achieved", "Acquired", "Activity", "Actually", "Addition", "Adequate", "Adjacent", "Adjusted",
    "Advanced", "Advisory", "Affected", "Aircraft", "Alliance", "Although", "Aluminum", "Analysis", "Announce", "Anything", "Apparent", "Approach", "Approval", "Argument", "Artistic", 
    "Assembly", "Assuming", "Athletic", "Attached", "Attitude", "Attorney", "Audience", "Autonomy", "Aviation", "Bachelor", "Bacteria", "Baseball", "Bathroom", "Becoming", "Benefits", 
    "Birthday", "Boundary", "Breaking", "Breeding", "Building", "Bulletin", "Business", "Calendar", "Campaign", "Capacity", "Casualty", "Catching", "Category", "Ceremony", "Chairman", 
    "Champion", "Chemical", "Children", "Circular", "Civilian", "Clearing", "Clinical", "Clothing", "Collapse", "Colonial", "Colorful", "Commence", "Commerce", "Complain", "Complete", 
    "Composed", "Compound", "Compress", "Computer", "Conclude", "Concrete", "Conflict", "Confused", "Congress", "Consider", "Constant", "Consumer", "Continue", "Contract", "Contrast", 
    "Convince", "Corridor", "Coverage", "Creating", "Creation", "Creative", "Criminal", "Critical", "Crossing", "Cultural", "Customer", "Database", "Daughter", "Daylight", "Deadline", 
    "Deciding", "Decision", "Decrease", "Deferred", "Delegate", "Delicate", "Delivery", "Describe", "Designer", "Detailed", "Detector", "Determine", "Develops", "Diagnose", "Dialogue", 
    "Diameter", "Directly", "Director", "Disabled", "Disaster", "Disclose", "Discount", "Discover", "Discrete", "Dispatch", "Disposal", "Distance", "Distinct", "District", "Dividend", 
    "Division", "Doctrine", "Document", "Domestic", "Dominant", "Dominate", "Doubtful", "Dramatic", "Dressing", "Dropping", "Duration", "Dynamics", "Earnings", "Economic", "Educated", 
    "Effected", "Election", "Electric", "Eligible", "Emerging", "Emphasis", "Employee", "Endeavor", "Engaging", "Engineer", "Enormous", "Entering", "Entirely", "Entrance", "Envelope", 
    "Equality", "Equation", "Estimate", "Evaluate", "Evenings", "Evidence", "Exchange", "Exciting", "Exercise", "Explicit", "Exposure", "Extended", "External", "Facility", "Familiar", 
    "Featured", "Feedback", "Festival", "Finished", "Firewall", "Flagship", "Flexible", "Floating", "Football", "Foothill", "Forecast", "Forehead", "Formerly", "Fourteen", "Fraction", 
    "Fragment", "Franklin", "Frequent", "Friendly", "Frontier", "Function", "Generate", "Generous", "Genomics", "Governor", "Graduate", "Graphics", "Grounded", "Guidance", "Handling", 
    "Hardware", "Heritage", "Hesitate", "Historic", "Hospital", "Humanity", "Humidity", "Identity", "Ideology", "Imperial", "Incident", "Included", "Increase", "Indicate", "Indirect", 
    "Industry", "Informal", "Informed", "Inherent", "Initiate", "Innocent", "Inspired", "Instance", "Instruct", "Integral", "Intended", "Interact", "Interest", "Interior", "Internal", 
    "Interval", "Intimate", "Intranet", "Invasion", "Involved", "Isolated", "Judgment", "Junction", "Juvenile", "Keyboard", "Laughter", "Learning", "Lecturer", "Leftover", "Lifetime", 
    "Lighting", "Likewise", "Limiting", "Literacy", "Location", "Lifetime", "Magazine", "Magnetic", "Maintain", "Majority", "Marginal", "Maritime", "Marketing", "Marriage", "Material", 
    "Maturity", "Maximize", "Meantime", "Measured", "Medicine", "Medieval", "Membrane", "Merchant", "Midnight", "Military", "Minimize", "Minister", "Ministry", "Minority", "Mobility", 
    "Modeling", "Moderate", "Momentum", "Monetary", "Monopoly", "Moreover", "Motivate", "Mountain", "Movement", "Multiple", "National", "Negative", "Neighbor", "Neutrino", "Nominate", 
    "Northern", "Notation", "Novelist", "Numerous", "Observer", "Occasion", "Offender", "Offering", "Official", "Offspring", "Operator", "Opponent", "Opposite", "Optimism", "Optional", 
    "Ordering", "Ordinary", "Organize", "Original", "Overcome", "Overhead", "Overlook", "Overseas", "Overview", "Painting", "Parallel", "Parental", "Patience", "Peaceful", "Periodic", 
    "Personal", "Persuade", "Petition", "Physical", "Pipeline", "Platform", "Pleasant", "Pleasure", "Plumbing", "Pointing", "Policies", "Politics", "Portable", "Position", "Positive", 
    "Possible", "Possibly", "Potential", "Practice", "Precious", "Presence", "Preserve", "Pressure", "Previous", "Priority", "Probably", "Producer", "Profound", "Progress", "Property", 
    "Proposal", "Prospect", "Protocol", "Provided", "Provider", "Province", "Publicly", "Purchase", "Pursuing", "Quantity", "Question", "Rational", "Reaction", "Received", "Recently", 
    "Recovery", "Regional", "Register", "Relation", "Relative", "Relevant", "Reliable", "Relieved", "Religion", "Remember", "Reporter", "Republic", "Required", "Research", "Reserved", 
    "Resident", "Resolved", "Resource", "Response", "Restrict", "Revision", "Rigorous", "Romantic", "Sampling", "Scenario", "Schedule", "Sciences", "Scrutiny", "Seasonal", "Secondary", 
    "Security", "Sensible", "Sentence", "Separate", "Sequence", "Sergeant", "Shipping", "Shortage", "Shoulder", "Simplify", "Situated", "Software", "Solution", "Somebody", "Somewhat", 
    "Southern", "Speaking", "Specific", "Spectrum", "Sporting", "Standard", "Standing", "Standout", "Sterling", "Straight", "Strategy", "Strength", "Striking", "Struggle", "Stunning", 
    "Suburban", "Suitable", "Superior", "Supplier", "Supposed", "Surgical", "Surprise", "Survival", "Sweeping", "Swimming", "Symbolic", "Sympathy", "Syndrome", "Tactical", "Tailored", 
    "Takeover", "Taxation", "Teaching", "Terminal", "Terrific", "Textbook", "Textiles", "Thinking", "Thorough", "Threaten", "Together", "Tomorrow", "Tracking", "Training", "Transfer", 
    "Translate", "Traveled", "Triangle", "Ultimate", "Umbrella", "Universe", "Unlawful", "Unlisted", "Unlikely", "Unmanned", "Unsigned", "Unwanted", "Upgrade", "Upstairs", "Vacation", 
    "Valuable", "Variable", "Vertical", "Violence", "Volatile", "Volunteer", "Wardrobe", "Warranty", "Weakness", "Widespread", "Wildlife", "Withdraw", "Withheld", "Workshop", "Worldwide", 
    "Yourself", "Zealotry" 
];

const nineLetterWords = [
    "abduction", "absorbent", "abstracts", "acclaimed", "accordant", "admirable", "admission", "adversity", 
    "aesthetic", "affection", "aggregate", "algorithm", "alligator", "alternate", "ambitious", "anachrony", 
    "anecdotes", "animosity", "apparatus", "appraisal", "approving", "arbitrary", "aristocrat", "arithmetic", 
    "artillery", "assemblage", "assistant", "attention", "authority", "automatic", "awareness", "backstage", 
    "balancing", "battalion", "beautiful", "benchmark", "bewildered", "biography", "blacksmith", "blasphemy", 
    "brilliant", "broadband", "broadcast", "brokerage", "browsable", "buildings", "calculate", "candidate", 
    "canonical", "carefully", "cartoonist", "celebrate", "celebrity", "centenary", "centrifuge", "certainty", 
    "challenge", "chemistry", "childhood", "chivalrous", "chronicle", "cigarette", "clarified", "classical", 
    "classroom", "clearing", "climbing", "closeness", "coherence", "collateral", "colleague", "collector", 
    "colorless", "combative", "comforter", "communism", "communist", "comparing", "compiling", "complaint", 
    "complexity", "composing", "computing", "conducive", "confident", "confusion", "congenial", "conjugate", 
    "connected", "consensus", "conserving", "consonant", "constancy", "constrain", "consulted", "consuming", 
    "container", "continuum", "contrived", "converted", "correlate", "corrosion", "councilor", "countable", 
    "creativity", "criminal", "criticize", "criterion", "crosswalk", "culminate", "curiosity", "customize", 
    "darkening", "daughters", "decidable", "dedicated", "defensive", "deficient", "definition", "delegated", 
    "delighted", "demanding", "democracy", "departing", "depiction", "depletion", "depression", "derogatory", 
    "desirable", "designing", "desirable", "determined", "detention", "developed", "devotional", "dignified", 
    "diligence", "direction", "disabling", "discharge", "discovery", "disguised", "dismissal", "disparate", 
    "disputing", "disregard", "distorted", "disturbed", "divergent", "diversity", "documented", "dominance", 
    "donations", "downgrades", "dynamical", "economical", "efficacy", "efficient", "embodiment", "emotional", 
    "empirical", "emulating", "endearing", "endeavors", "endlessly", "energizer", "enforcement", "enlarging", 
    "enlighten", "enlisting", "enormous", "enriching", "enumerated", "envision", "enwrapment", "ephemeral", 
    "epiphany", "equality", "equitable", "equipment", "erroneous", "escalator", "essential", "establish", 
    "estimable", "evaporate", "evocative", "excitement", "executive", "expansive", "explained", "exploring", 
    "extending", "extension", "extensive", "extortion", "extricate", "facilitate", "fascinate", "favorable", 
    "feedback", "fellowship", "fictitious", "fieldwork", "fireproof", "flattering", "flavorful", "flickering", 
    "following", "foolishly", "forecast", "forensics", "formation", "formative", "formidable", "forwarding", 
    "foundation", "fragments", "framework", "frequency", "frightful", "frustrate", "fulfilling", "function", 
    "galvanize", "glistened", "glorified", "governing", "gratitude", "guideline", "gullible", 
    "handsome", "harbinger", "harmonics", "healthcare", "heartfelt", "heaviness", "heightened", "hemisphere", 
    "hermitage", "hesitated", "hierarchy", "hilarious", "hindrance", "hospitable", "humanized", "humankind", 
    "hydration", "hysterical", "identical", "ignitable", "illuminating", "illusion", "imitation", "immensely", 
    "immigrant", "impartial", "important", "impressed", "improving", "inanimate", "inaugural", "incident", 
    "incurable", "indicated", "influence", "informing", "ingenious", "inhabited", "initially", "injection", 
    "injustice", "innovative", "inputting", "inquiry", "inspected", "inspiring", "installing", "instinct", 
    "institute", "integrate", "intensify", "intensity", "intercept", "interior", "interview", 
    "intuitive", "inventing", "inventory", "investment", "invisible", "invoking", "isolation", "itinerary", 
    "jubilance", "judgement", "justified", "knowledge", "landscape", "language", "larcenous", 
    "leadership", "learning", "legitimate", "liability", "liberated", "lightning", "likelihood", "limitation", 
    "linguistic", "literally", "localized", "longevity", "lucrative", "luminous", "magnified", "maintenance", 
    "manipulate", "marginal", "marketplace", "marvelous", "material", "measuring", "mediation", "medically", 
    "membership", "memorized", "mendacity", "mercenary", "methodical", "meticulous", "migration", "minimized", 
    "mirroring", "misconduct", "misguided", "mismanage", "modernize", "modulated", "monetary", "monitored", 
    "motivated", "movement", "multiplex", "municipal", "narrative", "necessary", "negotiable", "networked", 
    "nobleman", "nonchalant", "noticeable", "nourished", "nutrition", "obligation", "observance", "obsession", 
    "obsolete", "obstacles", "occupation", "offensive", "officially", "omnivorous", "operational", "opportune", 
    "oppressed", "optimistic", "organized", "ornamental", "oscillate", "outlawing", "outraging", "overacting", 
    "overheard", "overjoyed", "overlooked", "overrated", "overruled", "overthrow", "overturned", "overwhelmed", 
    "packaging", "painless", "paralyzed", "parameter", "parenting", "partially", "passenger", "pastoral", 
    "patchwork", "patriotic", "peculiarly", "perceived", "perfection", "performance", "permitted", "personage", 
    "persuaded", "philosophy", "physician", "pioneered", "placidity", "playfully", "plentiful", "political", 
    "populated", "portfolio", "position", "potential", "practiced", "preceding", "precision", "preferably", 
    "prejudiced", "preparing", "prescribed", "presented", "preserved", "presiding", "presumably", "prevalent", 
    "primarily", "principle", "privilege", "procedure", "processing", "production", "profoundly", "programmed", 
    "projected", "prolonged", "prominent", "promising", "promotion", "prompting", "proportion", "prosperity", 
    "protective", "providing", "provoking", "purchased", "qualifying", "qualities", "quantified", "quarterly", 
    "questions", "quotidian", "radiation", "realistic", "reasoning", "reception", "reciprocal", "recognize", 
    "recommend", "reconcile", "recreated", "reduction", "reference", "reflecting", "refundable", "regarding", 
    "regulated", "rehearsal", "reinforce", "reiterate", "relations", "relevance", "reliance", "relocated", 
    "remarkable", "reminding", "rendition", "renewable", "repayment", "repeating", "replicate", "reporting", 
    "reproduce", "repulsion", "requested", "residence", "resilient", "resistant", "resolving", "respectful", 
    "restraint", "revelation", "reverence", "revolution", "rhetorical", "righteous", "rigorously", "roleplaying", 
    "roughness", "roundabout", "rudimentary", "sacrament", "safeguard", "saturate", "satisfied", "saturated", 
    "scattered", "scheduled", "scientific", "scintilla", "scripture", "scrupulous", "scrutinize", "seamlessly", 
    "searching", "secondary", "seduction", "selective", "sensation", "senseless", "sensitive", "sentiment", 
    "separated", "sequenced", "seriously", "settlement", "shattered", "sheltered", "sightless", "simplified", 
    "situation", "sociology", "solution", "sophomore", "sorrowful", "soundtrack", "sparingly", "specialist", 
    "specified", "speculate", "spherical", "spirituous", "sponsorship", "spreading", "sprinkled", "stability", 
    "standards", "statement", "stationed", "statutory", "sterilize", "stimulant", "stipulate", "storefront", 
    "storyline", "strategic", "structure", "submarine", "subsequent", "substitute", "subverting", "successful", 
    "sufficient", "suggestive", "summarize", "superior", "surcharge", "surrender", "surrounds", "surviving", 
    "suspicion", "sustaining", "swiftness", "syllables", "symbolism", "sympathetic", "syndrome", "synthesized", 
    "systematic", "tangible", "tasteless", "technical", "technique", "technology", "temporally", "temporary", 
    "terminated", "territory", "thankless", "theatrical", "theology", "therapist", "thoroughly", "threshold", 
    "tightened", "tolerable", "totalized", "traditional", "transcript", "transient", "translate", "transmit", 
    "transpire", "treatment", "treasured", "trending", "triangle", "triumphant", "troubling", "trusting", 
    "turbulent", "typifying", "ultimate", "umbrella", "unanimous", "unattractive", "uncharted", "uncovered", 
    "undeniable", "undetected", "undulating", "unequaled", "unethical", "ungrateful", "unhindered", "unification", 
    "universally", "unknowing", "unleashed", "unnerving", "unplanned", "unsettled", "unsparing", "unspoken", 
    "untouched", "unveiling", "unwavering", "unwrapped", "upgradeable", "upgrading", "uplifting", "uprooting", 
    "urbanized", "usefulness", "utilizing", "vacancies", "validates", "variances", "vegetable", "ventilator", 
    "versatile", "versified", "victimized", "videotape", "viewpoint", "violation", "virtually", "visualize", 
    "vocabulary", "voluntary", "vulnerability", "wanderlust", "warmhearted", "wavelength", "weakening", "weariness", 
    "widespread", "wilderness", "willingness", "withstand", "worrisome", "worshiped", "worthwhile", "yearnings", 
    "youngsters", "zealously", "zeppelins"
];

const nineLetterWordsCaps = [
    "Abduction", "Absorbent", "Abstracts", "Acclaimed", "Accordant", "Admirable", "Admission", "Adversity", "Aesthetic", "Affection", 
    "Aggregate", "Algorithm", "Alligator", "Alternate", "Ambitious", "Anachron", "Anecdotes", "Animosity", "Apparatus", "Appraisal",
    "Approving", "Arbitrary", "Aristocrat", "Arithmetic", "Artillery", "Assemblage", "Assistant", "Attention", "Authority", "Automatic",
    "Awareness", "Backstage", "Balancing", "Battalion", "Beautiful", "Benchmark", "Bewildered", "Biography", "Blacksmith", "Blasphemy",
    "Brilliant", "Broadband", "Broadcast", "Brokerage", "Browsable", "Buildings", "Calculate", "Candidate", "Canonical", "Carefully", 
    "Cartoonist", "Celebrate", "Celebrity", "Centenary", "Centrifuge", "Certainty", "Challenge", "Chemistry", "Childhood", "Chivalrous", 
    "Chronicle", "Cigarette", "Clarified", "Classical", "Classroom", "Clearance", "Closeness", "Coherence", "Collateral", "Colleague", 
    "Collector", "Colorless", "Combative", "Comforter", "Communism", "Communist", "Comparing", "Compiling", "Complaint", "Complexity",
    "Composing", "Computing", "Conducive", "Confident", "Confusion", "Congenial", "Conjugate", "Connected", "Consensus", "Conserving", 
    "Consonant", "Constancy", "Constrain", "Consulted", "Consuming", "Container", "Continuum", "Contrived", "Converted", "Correlate",
    "Corrosion", "Councilor", "Countable", "Creativity", "Criminal", "Criticize", "Criterion", "Crosswalk", "Culminate", "Curiosity",
    "Customize", "Darkening", "Daughters", "Decidable", "Dedicated", "Defensive", "Deficient", "Definition", "Delegated", "Delighted", 
    "Demanding", "Democracy", "Departing", "Depiction", "Depletion", "Depression", "Derogatory", "Desirable", "Designing", "Determined", 
    "Detention", "Developed", "Devotional", "Dignified", "Diligence", "Direction", "Disabling", "Discharge", "Discovery", "Disguised", 
    "Dismissal", "Disparate", "Disputing", "Disregard", "Distorted", "Disturbed", "Divergent", "Diversity", "Documented", "Dominance", 
    "Donations", "Downgrades", "Dynamical", "Economical", "Efficiency", "Embodiment", "Emotional", "Empirical", "Emulating", "Endearing", 
    "Endlessly", "Energizer", "Enforcement", "Enlarging", "Enlighten", "Enlisting", "Enormous", "Enriching", "Enumerated", "Envision",
    "Envelopment", "Ephemeral", "Epiphany", "Equality", "Equitable", "Equipment", "Erroneous", "Escalator", "Essential", "Establish", 
    "Estimable", "Evaporate", "Evocative", "Excitement", "Executive", "Expansive", "Explained", "Exploring", "Extending", "Extension",
    "Extensive", "Extortion", "Extricate", "Facilitate", "Fascinate", "Favorable", "Feedback", "Fellowship", "Fictitious", "Fieldwork", 
    "Fireproof", "Flattering", "Flavorful", "Flickering", "Following", "Foolishly", "Forecast", "Forensics", "Formation", "Formative", 
    "Formidable", "Forwarding", "Foundation", "Fragments", "Framework", "Frequency", "Frightful", "Frustrate", "Fulfilling", "Function", 
    "Galvanize", "Healthcare", "Heartfelt", "Heaviness", "Heightened", "Hemisphere", "Hermitage", "Hesitated", "Hierarchy", "Hilarious", 
    "Hindrance", "Hospitable", "Humanized", "Humankind", "Hydration", "Hysterical", "Identical", "Ignitable", "Illuminating", "Illusion", 
    "Imitation", "Immensely", "Immigrant", "Impartial", "Important", "Impressed", "Improving", "Inanimate", "Inaugural", "Incident",
    "Incurable", "Indicated", "Influence", "Informing", "Ingenious", "Inhabited", "Initially", "Injection", "Injustice", "Innovative", 
    "Inputting", "Inquiry", "Inspected", "Inspiring", "Installing", "Instinct", "Institute", "Integrate", "Intensify", "Intensity", 
    "Intercept", "Interior", "Interview", "Intuitive", "Inventing", "Inventory", "Investment", "Invisible", "Invoking", "Isolation", 
    "Itinerary", "Jubilance", "Judgement", "Justified", "Knowledge", "Landscape", "Language", "Larcenous", "Leadership", "Legitimate", 
    "Liability", "Liberated", "Lightning", "Likelihood", "Limitation", "Linguistic", "Literally", "Localized", "Longevity", "Lucrative",
    "Luminous", "Magnified", "Maintenance", "Manipulate", "Marginal", "Marvelous", "Material", "Measuring", "Mediation", "Medically", 
    "Membership", "Memorized", "Mendacity", "Mercenary", "Methodical", "Meticulous", "Migration", "Minimized", "Mirroring", "Misconduct", 
    "Misguided", "Mismanage", "Modernize", "Modulated", "Monetary", "Monitored", "Motivated", "Movement", "Multiplex", "Municipal", 
    "Narrative", "Necessary", "Negotiable", "Networked", "Nobleman", "Nonchalant", "Noticeable", "Nourished", "Nutrition", "Obligation", 
    "Observance", "Obsession", "Obsolete", "Obstacles", "Occupation", "Offensive", "Officially", "Omnivorous", "Operational", "Opportune", 
    "Oppressed", "Optimistic", "Organized", "Ornamental", "Oscillate", "Outlawing", "Outraging", "Overacting", "Overheard", "Overjoyed", 
    "Overlooked", "Overrated", "Overruled", "Overthrow", "Overturned", "Packaging", "Painless", "Paralyzed", "Parameter", "Parenting", 
    "Partially", "Passenger", "Pastoral", "Patchwork", "Patriotic", "Peculiarly", "Perceived", "Perfection", "Performance", "Permitted", 
    "Personage", "Persuaded", "Philosophy", "Physician", "Pioneered", "Placidity", "Playfully", "Plentiful", "Political", "Populated", 
    "Portfolio", "Position", "Potential", "Practiced", "Preceding", "Precision", "Preferably", "Prejudiced", "Preparing", "Prescribed",
    "Presented", "Preserved", "Presiding", "Presumably", "Prevalent", "Primarily", "Principle", "Privilege", "Procedure", "Processing",
    "Production", "Profoundly", "Programmed", "Projected", "Prolonged", "Prominent", "Promising", "Promotion", "Prompting", "Proportion", 
    "Prosperity", "Protective", "Providing", "Provoking", "Purchased", "Qualifying", "Qualities", "Quantified", "Quarterly", "Questions", 
    "Quotidian", "Radiation", "Realistic", "Reasoning", "Reception", "Reciprocal", "Recognize", "Recommend", "Reconcile", "Recreated", 
    "Reduction", "Reference", "Reflecting", "Refundable", "Regarding", "Regulated", "Rehearsal", "Reinforce", "Reiterate", "Relations", 
    "Relevance", "Reliance", "Relocated", "Remarkable", "Reminding", "Rendition", "Renewable", "Repayment", "Repeating", "Replicate", 
    "Reporting", "Reproduce", "Repulsion", "Requested", "Residence", "Resilient", "Resistant", "Resolving", "Respectful", "Restraint", 
    "Revelation", "Reverence", "Revolution", "Rhetorical", "Righteous", "Rigorously", "Roughness", "Roundabout", "Rudimentary", "Sacrament",
    "Safeguard", "Saturated", "Scattered", "Scheduled", "Scientific", "Scintilla", "Scripture", "Scrupulous", "Scrutinize", "Seamlessly",
    "Searching", "Secondary", "Seduction", "Selective", "Sensation", "Senseless", "Sensitive", "Sentiment", "Separated", "Sequenced",
    "Seriously", "Settlement", "Shattered", "Sheltered", "Sightless", "Simplified", "Situation", "Sociology", "Solution", "Sophomore", 
    "Sorrowful", "Soundtrack", "Sparingly", "Specialist", "Specified", "Speculate", "Spherical", "Spirituous", "Sponsorship", "Spreading", 
    "Sprinkled", "Stability", "Standards", "Statement", "Stationed", "Statutory", "Sterilize", "Stimulant", "Stipulate", "Storefront", 
    "Storyline", "Strategic", "Structure", "Submarine", "Subsequent", "Substitute", "Subverting", "Successful", "Sufficient", "Suggestive", 
    "Summarize", "Superior", "Surcharge", "Surrender", "Surrounds", "Surviving", "Suspicion", "Sustaining", "Swiftness", "Syllables", 
    "Symbolism", "Sympathetic", "Syndrome", "Synthesized", "Systematic", "Tangible", "Tasteless", "Technical", "Technique", "Technology", 
    "Temporally", "Temporary", "Terminated", "Territory", "Thankless", "Theatrical", "Theology", "Therapist", "Thoroughly", "Threshold",
    "Tightened", "Tolerable", "Totalized", "Traditional", "Transcript", "Transient", "Translate", "Transmit", "Treatment", "Treasured", 
    "Trending", "Triangle", "Triumphant", "Troubling", "Trusting", "Turbulent", "Typifying", "Ultimate", "Umbrella", "Unanimous",
    "Uncharted", "Uncovered", "Undeniable", "Undetected", "Undulating", "Unequaled", "Unethical", "Ungrateful", "Unhindered", "Unification", 
    "Unleashed", "Unnerving", "Unplanned", "Unsettled", "Unsparing", "Unspoken", "Untouched", "Unveiling", "Unwavering", "Unwrapped", 
    "Upgradeable", "Upgrading", "Uplifting", "Uprooting", "Urbanized", "Usefulness", "Utilizing", "Vacancies", "Validates", "Variances", 
    "Vegetable", "Ventilator", "Versatile", "Versified", "Victimized", "Videotape", "Viewpoint", "Violation", "Virtually", "Visualize", 
    "Vocabulary", "Voluntary", "Wavelength", "Weakening", "Weariness", "Widespread", "Wilderness", "Willingness", "Withstand", "Worrisome", 
    "Worshiped", "Yearnings", "Youngsters", "Zealously", "Zeppelins"
];

export {
    specialChars,
    nums,
    twoLetterWords,
    twoLetterWordsCaps,
    threeLetterWords,
    threeLetterWordsCaps,
    fourLetterWords,
    fourLetterWordsCaps,
    fiveLetterWords,
    fiveLetterWordsCaps,
    sixLetterWords,
    sixLetterWordsCaps,
    sevenLetterWords,
    sevenLetterWordsCaps,
    eightLetterWords,
    eightLetterWordsCaps,
    nineLetterWords,
    nineLetterWordsCaps,
  };
  